### ISSUE TITLE
[BUG] Programmer Art Injector causing intermittent crashes on Quilt

### ISSUE THREAD

**Issue by justastranger** [DaFuqs/Spectrum#125]
**Describe the bug**
Upon loading the world, the game will usually (but not always) crash, always with the same error. I reported this crash to their github issues as well, but if they don't fix it upstream it might necessitate removing that library and presenting the resources you're injecting into it as a standalone resource pack (maybe using something like ARRP or its successor(s)).

**To Reproduce**
1. Use Quilt 1.17.4 through 1.17.5-beta.9
2. Create a world
3. Save and close the game
4. Open the game again and load the save
5. Repeat 3 and 4 a couple times and you should crash at least half the time.

**Expected behavior**
My save game loading fine each time I try

**Mod version**
Spectrum: 1.5.7-1.19.2-magic
owo-lib: 08.5-1.19
Revelationary: 1.0.2
Quilted Fabric API: 4.0.0-beta.15-0.63.0-1.19.2
Trinkets: 3.4.0
Patchouli: 1.19.2-77-FABRIC

**Crash Report**
[Crash Log](https://paste.ee/p/6AKfg)
[Crash Report](https://paste.ee/p/8Wiyh)

**Comment by justastranger** [comment]
It's worth noting that Programmer Art Injector has not received _any_ commits since 2020. Even if it's on their end, it's probably not getting fixed and that creates an issue on your end.

**Comment by DaFuqs** [comment]
While Programmer ARt Injector may have issues on 1.19.2 the crash in your log rather stems from something that tinkers with sprite interpolation (which Programmer Art injector does not do). I know Incubus Concern does/did, so you might want to look at that, too.

**Comment by DaFuqs** [comment]
Trying it on quilt I can't seem to reproduce any issues or crashes whatsoever. Maybe another mod makes changes to texture packs in a way that is incompatible? No idea, sorry

**Comment by CitadelCore** [comment]
Same issue here. It appears to require SemanticVersionPredicateParser.

```
[07:11:17] [main/ERROR]: Error loading companion plugin class [com.extracraftx.minecraft.programmerartinjector.MixinPlugin] for mixin config [programmerartinjector.mixins.json]. The plugin may be out of date: NoClassDefFoundError:net/fabricmc/loader/util/version/SemanticVersionPredicateParser
java.lang.NoClassDefFoundError: net/fabricmc/loader/util/version/SemanticVersionPredicateParser
	at com.extracraftx.minecraft.programmerartinjector.MixinPlugin.<clinit>(MixinPlugin.java:25) ~[ProgrammerArtInjector-1.2.1.jar-0077a03f-0c3f-4b9e-bc8b-8c3533e29c07-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[quilt-loader-0.17.7.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:278) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:153) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:182) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:161) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.util.version.SemanticVersionPredicateParser
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 27 more
```
