### ISSUE TITLE
Game Crashes when adding Spectrum

### ISSUE THREAD

**Issue by C3veron** [DaFuqs/Spectrum#197]
**Describe the bug**

tried adding the game to my mod folder, via curseforge, game crashes. something "extshape"

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A concise description of what you expected to happen.

the game starting

**Mod version**
Which version of the mod are you currently using?

1.6.9

**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extshape'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class de.dafuqs.spectrum.registries.SpectrumItems
		at de.dafuqs.spectrum.SpectrumCommon.onInitialize(SpectrumCommon.java:143)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 7 more

**Comment by DaFuqs** [comment]
Can you attach the full log, please? Sounds like some mod messes with mod load order

**Comment by C3veron** [comment]
No need...I found the mod that screwed it up... it is actually the mod "extended block shape" -> "extshape" .. sorry for taking your time ^^"

**Comment by DaFuqs** [comment]
No problem at all. Glad it worked out so quickly then. Have fun!

**Comment by C3veron** [comment]
Keep up the good work with spectrum, really awesome mod ;)
