### ISSUE TITLE
java.io.FileNotFoundException: spectrum:textures/entity/lizard.png

### ISSUE THREAD

**Issue by inikishev** [DaFuqs/Spectrum#199]
**Describe the bug**
```
[14:03:56] [Render thread/WARN]: Failed to load texture: spectrum:textures/entity/lizard.png
java.io.FileNotFoundException: spectrum:textures/entity/lizard.png
	at net.minecraft.class_5912.method_43043(class_5912.java:20) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:239) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:36) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:956) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:750) ~[client-intermediary.jar:?]
	at net.raphimc.immediatelyfast.feature.core.BatchableImmediate._draw(BatchableImmediate.java:37) ~[ImmediatelyFast-1.1.12+1.19.jar:?]
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22994(ImmediateAdapter.java:120) ~[ImmediatelyFast-1.1.12+1.19.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?]
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_37104(ImmediateAdapter.java:93) ~[ImmediatelyFast-1.1.12+1.19.jar:?]
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22993(ImmediateAdapter.java:103) ~[ImmediatelyFast-1.1.12+1.19.jar:?]
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:276) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.CachedEntryListRender.prepare(CachedEntryListRender.java:165) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.CachedEntryListRender.get(CachedEntryListRender.java:113) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:88) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:346) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:244) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$1(DefaultScreenOverlayRenderer.java:65) ~[RoughlyEnoughItems-9.1.619.jar:?]
	at net.minecraft.class_465.handler$bab000$architectury$renderBackground(class_465.java:2240) [client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:100) [client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:27) [client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:90) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```

**Mod version**
1.7.0-deeper-down-alpha14

**Crash Report**
[If it is a crash bug add your crash log here](https://gist.github.com/stunlocked1/7207266d0a9f1bcb53af630b23829609)

**Comment by DaFuqs** [comment]
You are running a very unfinished alpha version that should only be used for testing. Be prepared for missing textures, unfinished content & bugs.
The mentioned texture (and this creature in general) will be finished in one of the later alphas.

**Comment by inikishev** [comment]
I see. The thing is prism launch downloads it by default. I need to open an issue in their github ig

**Comment by DaFuqs** [comment]
They now have their finished model + textures in alpha-21!
