### ISSUE TITLE
[BUG] Spectrum is causing Sawmill mod to crash on server

### ISSUE THREAD

**Issue by Trent2087** [DaFuqs/Spectrum#341]
**Describe the bug**
Using the Sawmill mods Sawmill block crashes on servers. No issue without Spectrum.

**To Reproduce**
Have both Spectrum and Sawmill mods.
Use the Sawmill mods Sawmill block on a server. 
(https://github.com/MehVahdJukaar/sawmill)

**Expected behavior**
Not causing another mod to call client code

**Mod version**
1.7.4

**Crash Report**
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/MinecraftClient
	at de.dafuqs.spectrum.registries.SpectrumItemGroups.lambda$static$4(SpectrumItemGroups.java:394)
	at de.dafuqs.fractal.api.ItemSubGroup.updateEntries(ItemSubGroup.java:38)
	at net.minecraft.item.ItemGroups.mdc60a03$fractal$lambda$updateEntries$0$0(ItemGroups.java:2629)
	at net.minecraft.item.ItemGroups.updateDisplayContext(ItemGroups.java:2063)
	at net.mehvahdjukaar.sawmill.RecipeSorter.refreshIfNeeded(RecipeSorter.java:31)
    Caused by: java.lang.ClassNotFoundException: net.minecraft.client.MinecraftClient
```
(https://hastebin.com/share/itefesogel.yaml)

**Comment by DaFuqs** [comment]
How did that ever work

**Comment by DaFuqs** [comment]
Quality bug report as always, ty!
