### ISSUE TITLE
[BUG] Crash when loading an existing world (with other mods) after rebooting client. "this.parent$this" is null (1.19.2 fabric)

### ISSUE THREAD

**Issue by AllieSniperian** [DaFuqs/Spectrum#353]
**Describe the bug**
The game would initially run fine and well, loading and creating a new world. But if the game client was closed and reopened, the game would crash when attempting to load a save. (This crash does not happen with Spectrum and Revelationary removed.)

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1058.method_4578()" because "this.parent$this" is null
	at net.minecraft.class_1058$class_4728.method_24128(class_1058.java:1540)
	at net.minecraft.class_1058$class_5790.method_4622(class_1058.java:441)
	at net.minecraft.class_1059.method_4612(class_1059.java:263)
	at net.minecraft.class_1059.method_4622(class_1059.java:272)
	at net.minecraft.class_1060.method_4622(class_1060.java:160)
	at net.minecraft.class_310.method_1574(class_310.java:1803)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**To Reproduce**
1; Create a new world
2; Close Client
3; Reopen Client
4; Open the same world.
5; [Crash]

**Expected behavior**
The world to load normally, and be playable.

**Mod version**
Spectrum 1.7.6 - 1.19.2 fabric
Revelationary 1.3.5 - 1.19.2 fabric

**Crash Report**
If it is a crash bug add your crash log here
[crash-2024-02-21_12.46.34-client.txt](https://github.com/DaFuqs/Spectrum/files/14363822/crash-2024-02-21_12.46.34-client.txt)

Modrinth profile of the world in progress mod pack where the crash was experienced if the crash log proves insufficent.
https://drive.google.com/file/d/1h8G4Ppg2xHTgLm0EIYh8Okrk1l0L8AHm/view?usp=sharing

**Comment by eehunter** [comment]
`class_1058` refers to `TextureAtlasSprite`, and `method_4578` is `getWidth`. As far as I know, neither Spectrum nor Revelationary directly interfere with that class. My best guess is that it's a conflict with Sodium, but I don't think I can contribute more than that for this particular issue.

**Comment by AllieSniperian** [comment]
> `class_1058` refers to `TextureAtlasSprite`, and `method_4578` is `getWidth`. As far as I know, neither Spectrum nor Revelationary directly interfere with that class. My best guess is that it's a conflict with Sodium, but I don't think I can contribute more than that for this particular issue.

Tried it without Sodium and Indium, and the same crash occurred.

**Comment by DaFuqs** [comment]
My only idea is that this is caused by some Incubus Concern yank, since that fucks with particle sprites. But I cannot tell by the crashlog exactly.

**Comment by gamerpotion** [comment]
Try to disable DashLoader mod and see if still crashing
