### ISSUE TITLE
Titration Barrel Crash

### ISSUE THREAD

**Issue by AIDcGH** [DaFuqs/Spectrum#359]
**Describe the bug**
Game crashes whenever I try to a recipe that doesn't include liquids
(like fresh chocolate)

**To Reproduce**
Inputting the correct ingredients for a non-liquid recipe into the barrel.

**Mod version**
Minecraft Version: 1.20.1
Operating System: Windows 11 (amd64) version 10.0
Java Version: 17.0.8, Microsoft

Spectrum 1.7.6

**Crash Report**
java.lang.AssertionError: Invalid FluidIngredient object
	at de.dafuqs.spectrum.recipe.FluidIngredient.test(FluidIngredient.java:107)
	at de.dafuqs.spectrum.blocks.titration_barrel.TitrationBarrelBlockEntity.canBeSealed(TitrationBarrelBlockEntity.java:271)
	at de.dafuqs.spectrum.blocks.titration_barrel.TitrationBarrelBlock.method_9534(TitrationBarrelBlock.java:97)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_3225.method_14262(class_3225.java:343)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Robotgiggle** [comment]
This is fixed in version 1.7.7 of Spectrum
