### ISSUE TITLE
[BUG] [1.19.2 - 1.7.11] Placing a Titation Barrel Vertically Hard Crashes the Game

### ISSUE THREAD

**Issue by TimeBender25** [DaFuqs/Spectrum#402]
**Describe the bug**
Looking up or down while trying to place a Titration Barrel will attempt to apply the "Up" or "Down" Blockstate, which is not an allowed value and will crash the client.

**To Reproduce**
1) Look up or down with a Titration Barrel in hand, jump if you must.
2) Attempt to place the Titation Barrel.

**Expected behavior**
Block does not get passed a state that crashes the game, instead behaving as a furnace does.

**Minecraft version**
1.19.2

**Mod version**
1.7.11

**Screenshots**
N/A

**Crash Report**

Looking Down:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-05-25 12:19:58
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{spectrum:titration_barrel}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:125)
	at de.dafuqs.spectrum.blocks.titration_barrel.TitrationBarrelBlock.method_9605(TitrationBarrelBlock.java:212)
	at net.minecraft.class_1747.method_7707(class_1747.java:119)
	at net.minecraft.class_1747.method_7712(class_1747.java:71)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:366)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

Looking Up:
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-05-25 12:33:25
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{spectrum:titration_barrel}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:125)
	at de.dafuqs.spectrum.blocks.titration_barrel.TitrationBarrelBlock.method_9605(TitrationBarrelBlock.java:212)
	at net.minecraft.class_1747.method_7707(class_1747.java:119)
	at net.minecraft.class_1747.method_7712(class_1747.java:71)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:366)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by DaFuqs** [comment]
Nice one! It should not be placeable vertically in the first place. Thank you!

**Comment by DaFuqs** [comment]
Fixed for next release. Ty!
