### ISSUE TITLE
[BUG] Opening "Colorful World" book crashes my server

### ISSUE THREAD

**Issue by tort-oise** [DaFuqs/Spectrum#453]
**Describe the bug**
Opening the guidebook crashes my server entirely, without any good explanation.

**To Reproduce**
Use Spectrum 1.8.0-alpha1. Create a remote server. Aquire the book, and open it. Server crashes, client game stays fine.

**Expected behavior**
My server shouldn't crash. I don't think I'm missing any dependencies.

**Minecraft version**
1.20.1

**Mod version**
Spectrum 1.8.0-alpha1

**Screenshots**
![image](https://github.com/user-attachments/assets/c341b6f1-4312-400c-a05f-87aa826df2dd)
![image](https://github.com/user-attachments/assets/224f4bb1-19e6-430f-9400-8c2f68b2d8ac)

**Crash Report**
```
[15:27:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_746
at de.dafuqs.spectrum.items. GuidebookItem.method_7836 (GuidebookItem.java:73) ~[spectrum-1.8.0-alpha1.jar:?]
at net.minecraft.class_1799.method_7913(class_1799.java:284) ~[server-intermediary.jar:?]
net.minecraft.class_3225.method_14256(class_3225.java:290) ~[server-intermediary.jar:?]
at
at net.minecraft.class_3244.method_12065 (class_3244.java:1177) ~[server-intermediary.jar:?]
at net.minecraft.class_2886.method_12550(class_2886.java:29) ~[server-intermediary.jar:?]
at net.minecraft.class_2886.method_11054 (class_2886.java:7) ~[server-intermediary.jar:?]
at net.minecraft.class_2600.method_11072 (class_2600.java:22) ~[server-intermediary.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18859 (class_1255.java:156) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.wrapOperation$cgm000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutor TaskExecuting (class_4093.java:570) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.method_18859 (class_4093.java:23) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_24306 (MinecraftServer.java:782) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_18859 (MinecraftServer.java:164) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075 (MinecraftServer.java:758) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_5383 (class_1255.java:115) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$zkd000$carpet$modified RunLoop (MinecraftServer.java:11451) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741 (MinecraftServer.java:650) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739 (MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
at jdk.internal.loader. Builtin ClassLoader.loadClass(Unknown Source) ~[?:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot. KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
23 more
```

**Comment by tort-oise** [comment]
Full server crash log (it wouldn't let me attach the .txt): 
[crash.zip](https://github.com/user-attachments/files/16589117/crash.zip)

**Comment by DaFuqs** [comment]
Fixed for the upcoming alpha2, thank you!

**Comment by tort-oise** [comment]
Thanks! Trying to play the mod without using the book was getting a bit annoying.
