### ISSUE TITLE
[Bug] blocks not dropping when broken

### ISSUE THREAD

**Issue by Laialot** [DaFuqs/Spectrum#529]
**Describe the bug**
while using the oblivion pickaxe along with ultimite to clear space in the nether, the pickaxe suddendly dissapeared from my inventory, then no block dropped when mined with any other tool

**To Reproduce**
when the bug occured i was using an oblivion pickaxe enchanted with efficiency 5, unbreaking 3 and mending, mining netherrack while keeping the ultimine key pressed down ine the large tunnel configuration. at the time i was playing with another player via LAN as the host. the other player noticed the blocks they were mining were not dropping.
the problem persisted when exiting the world, but closing minecraft and opening it again fixed it

**Minecraft version**
minecraft 1.20.1

**Mod version**
spectrum-1.7.16-deeper-down in Fabric

**Crash Report**
this seems to be the relevant bit of the log

[02:32:59] [Render thread/WARN]: Received passengers for unknown entity
[02:33:12] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@721a4c2d, suppressing error
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.remove(AbstractList.java:167) ~[?:?]
	at java.util.AbstractList$Itr.remove(AbstractList.java:387) ~[?:?]
	at java.util.AbstractList.removeRange(AbstractList.java:598) ~[?:?]
	at java.util.AbstractList.clear(AbstractList.java:243) ~[?:?]
	at net.minecraft.class_2248.modifyReturnValue$eap000$spectrum$getDroppedStacks(class_2248.java:5173) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9609(class_2248.java:333) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9511(class_2248.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9556(class_2248.java:431) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:275) ~[client-intermediary.jar:?]
	at dev.ftb.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:239) ~[ftb-ultimine-fabric-2001.1.5.jar:?]
	at net.minecraft.class_3225.handler$zei000$architectury$onBreak(class_3225.java:550) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:203) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1083) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:33:22] [Render thread/WARN]: Received passengers for unknown entity
[02:33:31] [Render thread/WARN]: Received passengers for unknown entity
[02:33:44] [Render thread/WARN]: Received passengers for unknown entity

**Comment by Azzyypaaras** [comment]
what

**Comment by Laialot** [comment]
tried to recreate the problem today in a copy of the world

at first i gave myself an oblivion pickaxe with commands, but it broke after only one use.
so i made one in the pedestal and gave myself xp to enchant it with books from my villagers.
went to the nether and started mining using ultimine and the problem ocurred again
as i don't know a lot about programing i can't be sure what is causing the problem, my intuition says it's either the pickaxe or ultimine but if anyone who knows more or can actually understand the logs could clarify it would be apreciated

i pasted the full log of this session here: [https://pastebin.com/Qe15cssT]
the problems occurs at around 11:40, at the end of the log as i closed the world after i recreated the bug

i also managed to record the gameplay when the problem happened and uploaded it here [https://www.youtube.com/watch?v=vf9MGFf6Jpw]

**Comment by GDPulsar** [comment]
what enchantments do the oblivion pickaxe have, and what do you think they do?

**Comment by Laialot** [comment]
> what enchantments do the oblivion pickaxe have, and what do you think they do?

just the normal vanilla enchantments, efficiency 5, unbreaking 3 and mending, plustthe curse of the void that comes with the pick

**Comment by Aeonsteel** [comment]
Rephrased: Do you think a pickaxe that voids drops and Curse of the Void might be related?

**Comment by f-raZ0R** [comment]
> what enchantments do the oblivion pickaxe have, and what do you think they do?

have you... watched the linked video? the bug is that after vein mining with the voiding pickaxe, the voiding is STILL APPLYING to other pickaxes

**Comment by Laialot** [comment]
> Rephrased: Do you think a pickaxe that voids drops and Curse of the Void might be related?

....yes? that is the reason i posted this here.
i believe you are not understanding what i'm saying or watched the video i posted, i know the oblivion pickaxe voids detroyed items, that is the reason i was using it to clear space in the nether looking for ancient debris, because i din't want all the netherrack, but one the bug ocurred, any block mined with any tool was voided, and not just for me, but also for another players who was connected via lan at the time

**Comment by f-raZ0R** [comment]
https://www.youtube.com/watch?v=vf9MGFf6Jpw
video with an actual link for the people who are too lazy to spend ten seconds to copy and paste it into their browser

**Comment by DaFuqs** [comment]
Note for me: class_2846 => PlayerActionC2SPacket

Looks like this does not occur with the latest Spectrum alpha.
Could you please run a test using that one?

I was using:
- Spectrum 1.8.0-alpha4
- Architectury 9.1.12
- FTB Ultimine v2001.1.5
- FTB Library v2001.2.4

**Comment by DaFuqs** [comment]
Looking at the Video again, there seems more at play. Maybe another mod is causing the issue, after all?
Curse of the Void spawns black particles on the block that was mined and drops are skipped. That is not the case in the video when the drops were breaking at the end.
