### ISSUE TITLE
CRASH while exploring (v 1.0.0-1.18.1-earlygame1)

### ISSUE THREAD

**Issue by CaiganMythFang** [DaFuqs/Spectrum#7]
While flying around in creative and exploring, I encountered a crash when it tries to load something in a chunk. Subsequent attempts to load the world after the crash just freezes the client with no crash when the surrounding chunks load (at least within the 15 minutes I left it alone)

First part of crash and stacktrace (full crash log included)
```
java.lang.ClassCastException: class net.minecraft.class_2435 cannot be cast to class de.dafuqs.spectrum.blocks.mob_head.SpectrumSkullBlock (net.minecraft.class_2435 and de.dafuqs.spectrum.blocks.mob_head.SpectrumSkullBlock are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @75cd8043)
	at net.minecraft.class_976.handler$eli000$render(class_976.java:534)
	at net.minecraft.class_976.method_17159(class_976.java:92)
	at net.minecraft.class_976.method_4199(class_976.java:33)
	at net.minecraft.class_922.redirect$zen000$preventFeatureRendering(class_922.java:563)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_839.method_3589(class_839.java:34)
	at net.minecraft.class_839.method_3569(class_839.java:12)
	at net.minecraft.class_824.method_23079(class_824.java:84)
	at net.minecraft.class_824.method_23081(class_824.java:73)
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at net.minecraft.class_761.method_22710(class_761.java:1368)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.redirect$ckc000$redirectRenderingWorld(class_757.java:5131)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
[crash-2021-12-16_10.19.37-client.txt](https://github.com/DaFuqs/Spectrum/files/7729811/crash-2021-12-16_10.19.37-client.txt)

Loading up with Spectrum disabled to stop the crash, seems that When Dungeons Arise mod has a mob spawner that summons zombies with player heads, and is probably where Spectrum crashes on.

Removing When Dungeons Arise (and re-enabling Spectrum) stops the game from just freezing, and instead will crash with the same report as above.

**Comment by DaFuqs** [comment]
Thank you for reporting that. I will fix it asap.
